### ISSUE TITLE
Structure

### ISSUE THREAD

**Issue by trvrb** [trvrb/sismid#1]
I'm making a separate directory for each top-level topic in the course outline. At the moment I plan for `wright-fisher`, `coalescent` and `flu` for day 2.

**Comment by trvrb** [comment]
This entire repo is now being mirrored to [bedford.io/projects/sismid/](http://bedford.io/projects/sismid/). You should be able to write README files in markdown that will render nicely in GitHub and also render nicely on the lab website. For a Markdown style guide, see:

http://bedford.io/guide/style/

Main notable addition is the ability to render math through MathJax.

**Comment by sarahCobey** [comment]
Thanks for all these updates--will be contributing tomorrow!

On Sunday, June 28, 2015, Trevor Bedford notifications@github.com wrote:

> This entire repo is now being mirrored to bedford.io/projects/sismid/.
> You should be able to write README files in markdown that will render
> nicely in GitHub and also render nicely on the lab website. For a Markdown
> style guide, see:
> 
> http://bedford.io/guide/style/
> 
> Main notable addition is the ability to render math through MathJax.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/trvrb/sismid/issues/1#issuecomment-116199517.

## 

---

Sarah Cobey, PhD
Assistant Professor
Ecology & Evolution
University of Chicago

(617) 756-7204 (cell)
sarahcobey (Skype)
cobeylab.uchicago.edu

**Comment by trvrb** [comment]
Looks like we got the basic structure down.
