### ISSUE TITLE
License? 

### ISSUE THREAD

**Issue by wrshoemaker** [trvrb/sismid#10]
Hello, 

I've been using the matplotlib code from your [WF repo](https://github.com/trvrb/sismid/tree/master/wright-fisher) for some special cases of the WF model I've been coding. I'd like to host this on GitHub with an MIT License, but I can't find a license on your repo. Do you plan on having one? If not I'll just write something different.

**Comment by trvrb** [comment]
Glad this is helpful. The Wright-Fisher notebook can definitely be MIT License. I'll get a license included for the repo as a whole shortly.

**Comment by trvrb** [comment]
@sarahCobey ---

Are you comfortable with licensing all slides as CC 4.0: http://choosealicense.com/licenses/cc-by-4.0/? 
And software as MIT: http://choosealicense.com/licenses/mit/?

If so, I'll add the licenses.

**Comment by sarahCobey** [comment]
Yes, that sounds good.

---

Sarah Cobey, PhD
Assistant Professor
Ecology & Evolution
University of Chicago

(617) 756-7204 (cell)
sarahcobey (Skype)
cobeylab.uchicago.edu
