### ISSUE TITLE
Pathogens and pathogen data

### ISSUE THREAD

**Issue by trvrb** [trvrb/sismid#11]
Possible pathogens to look at, roughly sorted in order of preference / data availability:
- ~~HIV (Trevor)~~
- ~~pneumo (Sarah)~~
- ~~dengue (Trevor)~~
- ~~malaria (Sarah)~~
- ~~enterovirus 71, including Polio (Sarah)~~
- ~~rotavirus (Sarah)~~
- ~~norovirus (Trevor)~~
- coronavirus (Trevor)
- ~~swine flu (Trevor)~~
- bird flu (Trevor)
- cholera (Sarah)
- Shigella
- Typhoid
- herpes virus, EBV, HSV, etc...

**Comment by trvrb** [comment]
@sarahCobey ---

Questions:
1. Should we be providing data for some of these pathogens in the repo? I think yes, but is this just links out to papers? Or is it actual data we want people analyzing? We can, of course, encourage google scholar, but I don't think we should rely on this.
2. Are we trying to give groups time at the end of lectures to discuss their pathogen? In which case are there 3 discussion periods, after:
- Day 1, Session C: Serology and antigenic evolution (Trevor)
- Day 2, Session A: Timeseries and fitting (Sarah)
- Day 2, Session C: Selection (Trevor)

for serology, timeseries and trees respectively?

**Comment by sarahCobey** [comment]
> Should we be providing data for some of these pathogens in the repo? I think yes, but is this just links out to papers? Or is it actual data we want people analyzing? We can, of course, encourage google scholar, but I don't think we should rely on this.

Supplying material in the repo will save valuable time in class. Asking people to analyze (i.e., perform computations on) time series and alignments would probably be too much--although maybe there are small exercises we could pick off. I suggest we rely mostly on figures from published papers, or perhaps the papers themselves. I'm still fuzzy on exactly what kinds of inference we expect them to make, but I will try to figure this out in the next day or two.

> Are we trying to give groups time at the end of lectures to discuss their pathogen? In which case are there 3 discussion periods, after:
> 
> Day 1, Session C: Serology and antigenic evolution (Trevor)
> Day 2, Session A: Timeseries and fitting (Sarah)
> Day 2, Session C: Selection (Trevor)

This makes sense. Some groups may not have much to present after some sections, but that's okay. Perhaps they could also speculate what would be necessary for forecasting.

**Comment by trvrb** [comment]
> This makes sense. Some groups may not have much to present after some sections, but that's okay. Perhaps they could also speculate what would be necessary for forecasting.

Ah. So you're thinking for groups to give 3 small reports and then a synthesis on Day 3?

> Perhaps they could also speculate what would be necessary for forecasting.

I like it.

---

I think we should plan to give some time on Day 3 morning for groups to synthesize findings and figure out a presentation strategy.

**Comment by sarahCobey** [comment]
I had assumed (not sure why) that groups would discuss _and_ present after each of those three sessions, but a single synthesis period makes the most sense. If you'd like to move the synthesis period to the end of Day 2 and the forecasting to Day 3, that's fine with me. Both schedules look good.

**Comment by trvrb** [comment]
I think time wise, we'll need to plan on:

25-30 people / 3-4 people per group = ~8 groups \* 10 min per group = 80 min for synthesis presentations.

This would be a full session. I think Day 2 is already quite full. What if we try to do forecasting at the end of Day 2 and synthesis presentations at the beginning of Day 3?

**Comment by sarahCobey** [comment]
That sounds good. We leave roughly an hour in the forecasting session on
Day 2 for them to pull together their presentations.

---

Sarah Cobey, PhD
Assistant Professor
Ecology & Evolution
University of Chicago

(617) 756-7204 (cell)
sarahcobey (Skype)
cobeylab.uchicago.edu

**Comment by trvrb** [comment]
@sarahCobey --- Take a look at this: https://github.com/trvrb/sismid/tree/master/lineup/dengue

Do you think this is right sort of setup? If so, I'll start in on other pathogens tomorrow.

**Comment by sarahCobey** [comment]
I like it. I can do malaria, rota, pneumo, entero (might not get to it until tomorrow). Perhaps move cholera toward the top. I don't know much about its evolution, but the (bio/sero)types are interesting.

**Comment by trvrb** [comment]
That's great. Thanks Sarah. I'll work on things that aren't these today.

**Comment by trvrb** [comment]
Also, I thought we could suggest that groups add material to the repo's wiki (they should have access) and this way presentations can be referenced after the course.

**Comment by sarahCobey** [comment]
I like it.

---

Sarah Cobey, PhD
Assistant Professor
Ecology & Evolution
University of Chicago

(617) 756-7204 (cell)
sarahcobey (Skype)
cobeylab.uchicago.edu

**Comment by trvrb** [comment]
That's 8 pathogens. We have 22 official registrants. We might get a couple drop ins, but this still nicely gives 3 people per group.

**Comment by trvrb** [comment]
Closing for 2016.
