### ISSUE TITLE
Lecture on pathogen diversity

### ISSUE THREAD

**Issue by trvrb** [trvrb/sismid#12]
Need to pad out introductory lecture on pathogen diversity:

https://github.com/trvrb/sismid/tree/master/pathogens

Currently have slides specific to flu. Should generally incorporate background on:
- RNA viruses
- DNA viruses
- bacteria
- parasites / other

**Comment by trvrb** [comment]
@sarahCobey --- let me know if you think this is too detailed. I don't know as much about bacteria so remaining sections may be simpler.

**Comment by sarahCobey** [comment]
Looks great. If people do not seem interested in the detailed life cycles, then you can skim, but it's nice to have that kind of information there.
