### ISSUE TITLE
Lecture on timeseries analysis

### ISSUE THREAD

**Issue by trvrb** [trvrb/sismid#14]
I think we decided to merge 2015 lectures on `fitting` and `ssr` into a single `timeseries` lecture. Trying not to recapitulate POMP and instead focus on the concepts of how timeseries of interacting (interfering) pathogens will behave.

https://github.com/trvrb/sismid/tree/master/timeseries

**Comment by sarahCobey** [comment]
Yes, and I think the SSR content should be downplayed. (Some of it can go in the forecasting section.) We'll still need to cover POMP. Perhaps we can ask Betz what other modules our students will have attended.

**Comment by sarahCobey** [comment]
Lecture revised. It's long, but I think it will set the groups up nicely to review at least one modeling paper for their system. (I don't like the original fitting exercise.) I'll see what candidate papers I can dig up for different pathogens.

Feel free to reopen this issue if you want to see changes to the lecture.

**Comment by trvrb** [comment]
The revised lecture looks great.
