### ISSUE TITLE
Lecture on multistrain models

### ISSUE THREAD

**Issue by trvrb** [trvrb/sismid#17]
Revise lecture on multistrain models. I don't think a lot has to happen here.

https://github.com/trvrb/sismid/tree/master/models

**Comment by sarahCobey** [comment]
I think it's got all the basics, so I'll leave it for now and revise as ideas occur to me. I'm open to suggestions too. Is the plan that the students can still do some of the original exercises? I think the one [here](https://github.com/trvrb/sismid/tree/master/models/exercise) is useful.

**Comment by trvrb** [comment]
I think that exercise is really great. I like that it doesn't require more than Python to work.

**Comment by sarahCobey** [comment]
Great, I'll keep it.
