### ISSUE TITLE
Commit changes to wiki

### ISSUE THREAD

**Issue by mattk7** [trvrb/sismid#28]
Hi!

Is there a way to commit changes directly to the wiki from a local repo?
I successfully cloned the wiki, added and committed the changes, but I get a permission error when trying to push the changes (while I can edit the wiki from the website GUI).

Thanks,
Matteo

**Comment by trvrb** [comment]
Sorry to never respond. I've edited wiki pages before following: https://help.github.com/articles/adding-and-editing-wiki-pages-locally/. I don't know what's causing the permissions error.
