### ISSUE TITLE
Exercise scripts

### ISSUE THREAD

**Issue by trvrb** [trvrb/sismid#6]
For `models/exercise/`, it wasn't immediately clear where the scripts lay. In the README you say:

> Open `two_strain.py` and `plot_two_strain_ts.py` and examine the code. 

However, it's not clear where this code actually is. I'd suggest moving the exercise instructions to `models/exercise/README.md` and link out to the GitHub source code locations https://github.com/trvrb/sismid/blob/master/models/exercise/two_strain.py, etc...

Or just link to https://github.com/trvrb/sismid/tree/master/models/exercise near the beginning of the exercise instructions.

**Comment by sarahCobey** [comment]
Agreed--the files there now are mostly placeholders, which I haven't
finished migrating and organizing.

---

Sarah Cobey, PhD
Assistant Professor
Ecology & Evolution
University of Chicago

(617) 756-7204 (cell)
sarahcobey (Skype)
cobeylab.uchicago.edu

**Comment by trvrb** [comment]
Ah. Okay. Sounds great. I think this is all shaping out quite nicely.

**Comment by trvrb** [comment]
Looks good.
