### ISSUE TITLE
Reorganization for 2016

### ISSUE THREAD

**Issue by trvrb** [trvrb/sismid#9]
I wanted to write some notes on this now while the course is still fresh. I'd propose the following:

I would take over the first lecture that would incorporate the more biological material from "competition" and from "flu". This would aim to give an overview of different sorts of pathogens, and their strategies to escape immunity. Would touch on flu, HIV, malaria, HPV, rhinoviruses, etc... 

You'd follow with a biological oriented immunity lecture that would be basically the B cell lecture from day 3, but would cover T cells and adaptive immunity as well.

I feel like my weakest link was actually the BEAST exercise. A large proportion of people had done exactly this exercise the week before. And I didn't like the step-by-step nature it entails. Better to tell people it exists and they can do it on their own time. This would free up some time.

I'd propose replacing "serology" with a more general "antigenic evolution" section. I could cover serology and you could cover things like the Hensley age distribution story you talked about [here](http://bedford.io/projects/sismid/bcells/slides.html#/30).

I'm propose to end with a "synthesis" discussion / exercise where students are given timeseries, trees, antigenic maps for say EV 71 and they're supposed to come to some conclusions about what's going on. Or maybe have people break up into groups and each group studies a particular pathogen and then reports to the class. We'd supply figures for each pathogen. So everything would be interpretation rather than data gathering.

Notice also that this makes it so you don't have a completely full day 1 and I don't have a completely full day 2.
### Day 1
- Session A: Biological lecture on pathogens _(Trevor)_
- Session B: Biological lecture on immunity _(Sarah)_
- Session C: Epi Models _(Sarah)_
- Session D: Fitting _(Sarah)_
### Day 2
- Session A: SSR _(Sarah)_
- Session B: Coalescent _(Trevor)_
- Session C: Phylogenetics _(Trevor)_
- Session D: Selection _(Trevor)_
### Day 3
- Session A: Antigenic evolution _(Both)_
- Session B: Synthesis _(Both)_

**Comment by sarahCobey** [comment]
Excellent ideas!

The only change I might make to your proposal is to extend the epi fitting over two sessions, perhaps focusing on population time series in Session D of Day 1 and on longitudinal data in Session A of Day 2. It may not be worth spending time fitting population data if MIF remains the obvious choice, however. (I am performing head-to-head competitions of methods this summer, so I should have a better sense if this is the case in a few months.) Covering inference well seems more important than SSR.

I also plan to include more small quizzes and exercises throughout my sessions.

It might be worth framing each session in the first two days in the most problem-oriented way possible, e.g., "This pathogen has a lot of types/high genetic diversity/fast turnover. How do we know if immune-mediated selection is a cause?" We then discuss population genetic measures, inference from mechanistic models, etc., in the context of major hypotheses. We could even assign pathogens to groups randomly on the first day (without providing the data then) so people listen with a specific context in mind. It might even make sense to provide data incrementally, e.g., some pertinent immunology after the immunology session, time series after the time series session, etc., if it wouldn't fragment the day too much.

**Comment by trvrb** [comment]
I like the idea of group exercises on different pathogens interspersed throughout the module, with updates on different data / biological aspects in tune with the lecture material. These sessions could be just within-group discussion. The final session could be groups presenting a synthesis to the rest of the class.

My thoughts on fitting are as follows:

I'm not sure there's a lot of time to fully ingest how to do proper timeseries fitting. Like the BEAST module, people should just take the POMP module to cover this fully. Spending time on how we learn about competition between species via timeseries is, I think, key. This certainly includes mechanistic fits, but could also be basic things like general patterns of interference (H3 vs H1 flu seasons). Longitudinal infection / serological data seems extremely helpful for this as well. I wouldn't expect to teach how to do these fits, but you could look at some of the results that people have. One example is:

http://journals.plos.org/plosbiology/article?id=10.1371/journal.pbio.1002082

Although it's not actually longitudinal, it's the sort of fit that should be quite informative of strain interactions.

**Comment by sarahCobey** [comment]
Those are good ideas. In general, it sounds like a broader integration of
different methods for inferring strain interaction, including longitudinal,
time series, and cross-sectional data, would be useful; pathogens differ in
the kinds of data available, creating different puzzles. This will be fun
to put together.

---

Sarah Cobey, PhD
Assistant Professor
Ecology & Evolution
University of Chicago

(617) 756-7204 (cell)
sarahcobey (Skype)
cobeylab.uchicago.edu

**Comment by trvrb** [comment]
### Day 1
- Session A: Biological lecture on pathogens _(Trevor)_
- Session B: Biological lecture on immunity _(Sarah)_
- Session C: Serology and antigenic evolution _(Trevor)_
- Session D: Epi Models _(Sarah)_

### Day 2
- Session A: Timeseries and fitting _(Sarah)_
- Session B: The Coalescent and phylogenetics _(Trevor)_
- Session C: Selection _(Trevor)_
- Session D: Forecasting _(Sarah mostly)_

### Day 3
- Session A: Synthesis _(Both)_
- Session B: B cell _(Sarah_)

**Comment by trvrb** [comment]
@sarahCobey ---

I'm going to start in on this reorganization. This will take the form of moving slides around to fit the above outline. I have a question about how to treat the pathogen presentations, but I'm going to thread this in issue #11.

**Comment by trvrb** [comment]
That's the basic reorganization. I think we should plan for **Forecasting** to be a short section as the other three things happening on day 2 are already quite time consuming. I agree that it's a good angle. I'm going to open issues on specific sections that need to be padded out.

**Comment by trvrb** [comment]
I think we're there with the basic reorganization. There are pieces that could be improved, but I'll leave these to separate issues.
